# Site
title:              Rohit Nair
bio:                'Programmer and Problem Solver.'
description:        "The Website provides a snapshot of my skills and activities."
reading_time:       true
words_per_minute:   125
logo:               'assets/img/profilePic.jpg'
background:         'assets/img/placeholder-big.jpg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
#url:                http://127.0.0.1:4000/
url:                https://rohitnair987.github.io/

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   Rohit

# Social
email:              rohitnair987@gmail.com
twitter:            theRohster
facebook:           rohitnair987
github-url:         rohitnair987
#stackoverflow:     5348988/rohit-nair   from a "http://stackoverflow.com/users/123456/username" link
linkedin:           www.linkedin.com/in/rohitnair987
instagram:          the_rohster
#youtube:           username
#youtube-channel:   channel

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
